
#pragma once

#define RPL_WELCOME			 "001"
#define ERR_NONICKNAMEGIVEN	 "431"
#define ERR_ERRONEUSNICK	 "432"
#define ERR_NICKNAMEINUSE	 "433"
#define ERR_NEEDMOREPARAMS	 "461"
#define ERR_ALREADYREGISTRED "462"
#define ERR_PASSWDMISMATCH	 "464"
